sudo: false

language: php

branches:
    only:
        - master
php:
    - 5.3
    - 5.6
    - 7.0

env:
    - WP_VERSION=master
    - WP_VERSION=4.5
    - WP_VERSION=4.4

matrix:
    fast_finish: true

before_script:
    - export WP_TESTS_DIR=/tmp/wordpress/tests/phpunit
    - export WP_CORE_DIR=/tmp/wordpress/src/
    - git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp /tmp/wordpress/wp-tests-config-sample.php /tmp/wordpress/wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" /tmp/wordpress/wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" /tmp/wordpress/wp-tests-config.php
    - sed -i "s/yourpasswordhere//" /tmp/wordpress/wp-tests-config.php

script:
    - find . -type "f" -iname "*.php" | xargs -L "1" php -l; fi
    - phpunit
    - export WP_MULTISITE=1 && phpunit
